[package]
name = "attestation-daemon"
version = "0.1.0"
authors = ["Lily Sturmann <lsturman@redhat.com>"]
edition = "2019"

[dependencies]
openssl = "0.10.23"
hex = "0.3.1"
sgx-isa = "0.3.1"
dcap-ql = "0.2.0"
