[workspace]
members = ['attestation-enclave', 'attestation-daemon', 'attestation-tenant']

[patch.crates-io]
dcap-ql = { path = "../../rust-sgx/dcap-ql" }
sgx-isa = { path = "../../rust-sgx/sgx-isa" }
