[workspace]
members = ['attestation-enclave', 'attestation-daemon', 'attestation-tenant']

[patch.crates-io]
dcap-ql = { git = "https://github.com/lkatalin/rust-sgx", branch = "serde-pck" }
sgx-isa = { git = "https://github.com/lkatalin/rust-sgx", branch = "serde-pck"}
