[package]
name = "sgx-demo"
version = "0.1.0"
authors = ["LKatalin"]
edition = "2018"

[workspace]
members = ['attestation-enclave', 'attestation-daemon', 'attestation-tenant']

[dependencies]
sgx-isa = "0.3.1"
dcap-ql = "0.2.0"
